import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";

test("client implements the required story surfaces", async () => {
  const page = await readFile("app/page.tsx", "utf8");
  const layout = await readFile("app/layout.tsx", "utf8");
  const experience = await readFile("components/HiddenBitesExperience.tsx", "utf8");
  const qnaAccordion = await readFile("components/QnaAccordion.tsx", "utf8");
  const kakaoMap = await readFile("components/KakaoMap.tsx", "utf8");
  const scorePlot = await readFile("components/ScorePlot.tsx", "utf8");
  const seoulMap = await readFile("components/SeoulRestaurantMap.tsx", "utf8");
  const reportPanel = await readFile("components/RestaurantReportPanel.tsx", "utf8");
  const css = await readFile("app/globals.css", "utf8");

  assert.match(page, /HiddenBitesExperience/);
  assert.match(experience, /story-section--hero/);
  assert.match(experience, /story-section--question/);
  assert.match(experience, /story-section--qna/);
  assert.match(experience, /story-section--scores/);
  assert.match(experience, /story-section--report/);
  assert.match(experience, /story-section--map/);
  assert.match(experience, /story-section--limitations/);
  assert.match(experience, /00 INTRO/);
  assert.match(experience, /03 HB SCORE/);
  assert.match(experience, /05 REMAPping/);
  assert.match(experience, /06 Limitation/);
  assert.match(experience, /<strong>Data visualization project<\/strong>/);
  assert.match(experience, /Sogang University Art&Technology/);
  assert.match(experience, /QnaAccordion/);
  assert.match(qnaAccordion, /useLayoutEffect/);
  assert.match(qnaAccordion, /ResizeObserver/);
  assert.match(qnaAccordion, /--qna-answer-height/);
  assert.match(qnaAccordion, /aria-controls=\{answerId\}/);
  assert.match(experience, /ScorePlot/);
  assert.match(experience, /SeoulRestaurantMap/);
  assert.match(experience, /RestaurantReportPanel/);
  assert.match(experience, /id="selected-report-restaurant-select"/);
  assert.match(experience, /className="selected-heading__select restaurant-select"/);
  assert.match(experience, /data\.restaurants\.map\(\(restaurant\) =>/);
  assert.match(experience, /restaurant\.displayPlaceName/);
  assert.match(experience, /onChange=\{\(event\) => handleSelectRestaurant\(event\.target\.value\)\}/);
  assert.doesNotMatch(experience, /<span>\{selectedRestaurant\?\.placeName \?\? "Restaurant"\}<\/span>/);
  assert.match(scorePlot, /score-controls/);
  assert.match(scorePlot, /displayPlaceName/);
  assert.doesNotMatch(scorePlot, /tooltip\.score\.placeName|score\.placeName\}<\/strong>|topScore\?\.placeName|selectedScore\?\.placeName/);
  assert.match(scorePlot, /factor-weight-slider/);
  assert.match(scorePlot, /score-mode-toggle/);
  assert.match(scorePlot, /role="button"/);
  assert.match(seoulMap, /data-testid="seoul-map-chart"/);
  assert.match(seoulMap, /KakaoMap/);
  assert.match(seoulMap, /Seoul top restaurant Kakao map dot distribution/);
  assert.match(kakaoMap, /react-kakao-maps-sdk/);
  assert.match(kakaoMap, /CustomOverlayMap/);
  assert.match(kakaoMap, /useKakaoLoader/);
  assert.match(kakaoMap, /useRef/);
  assert.match(kakaoMap, /useCallback/);
  assert.match(kakaoMap, /didFitInitialBoundsRef/);
  assert.match(kakaoMap, /didFitInitialBoundsRef\.current = true/);
  assert.match(kakaoMap, /targetHash: "map"/);
  assert.match(kakaoMap, /NEXT_PUBLIC_KAKAO_MAP_API_KEY/);
  assert.match(kakaoMap, /restaurant\.latitude/);
  assert.match(kakaoMap, /restaurant\.longitude/);
  assert.match(kakaoMap, /restaurant\.displayPlaceName/);
  assert.doesNotMatch(kakaoMap, /restaurant\.placeName|activeRestaurant\.placeName/);
  assert.match(experience, /const nextHash = options\.targetHash \? `#\$\{options\.targetHash\}` : url\.hash/);
  assert.doesNotMatch(seoulMap, /<svg|<circle|projectPoint|seoulOutline|hanRiver/);
  assert.match(reportPanel, /restaurant-select/);
  assert.match(reportPanel, /report\.displayPlaceName/);
  assert.doesNotMatch(reportPanel, /report\.placeName|restaurant\.placeName/);
  assert.match(reportPanel, /keyword-chip/);
  assert.match(css, /100svh/);
  assert.match(css, /font-family: "WAGURI"/);
  assert.match(css, /WAGURITTF\.woff2/);
  assert.match(css, /font-family: "LeeSeoyun"/);
  assert.match(css, /LeeSeoyun\.woff/);
  assert.match(css, /font-family: "AirbnbCereal_W_Bd"/);
  assert.match(css, /font-family: "AirbnbCereal_W_XBd"/);
  assert.match(css, /unicode-range:/);
  assert.match(css, /U\+AC00-D7A3/);
  assert.match(css, /--font-body: "Sora", "Noto Sans KR", "Airbnb Cereal"/);
  assert.match(css, /--font-primary: var\(--font-body\);/);
  assert.match(css, /--font-display: "Bowlby One", "WAGURI", "Noto Sans KR", var\(--font-body\);/);
  assert.match(css, /--font-mono: "JetBrains Mono", "Noto Sans KR"/);
  assert.match(css, /--font-chart: "Inter", "Noto Sans KR"/);
  assert.match(css, /--font-airbnb-bold: "AirbnbCereal_W_Bd", "Airbnb Cereal", var\(--font-body\);/);
  assert.match(css, /--font-airbnb-extra-bold: "AirbnbCereal_W_XBd", "Airbnb Cereal", var\(--font-body\);/);
  assert.match(css, /body\s*\{[\s\S]*font-family: var\(--font-body\);/);
  assert.match(css, /\.hero-poster h1,[\s\S]*\.story-footer h2\s*\{[\s\S]*font-family: var\(--font-display\);/);
  assert.match(css, /\.story-section--hero\s*\{[\s\S]*padding-left: 2rem;[\s\S]*padding-right: 2rem;/);
  assert.match(css, /\.story-section--hero \.story-nav\s*\{[\s\S]*gap: 0;[\s\S]*justify-content: flex-start;[\s\S]*margin-bottom: clamp\(5rem, 7vw, 6\.75rem\);/);
  assert.match(css, /\.story-section--hero \.story-brand\s*\{\s*display: block;\s*\}/);
  assert.match(css, /\.story-section--hero \.story-nav__links\s*\{[\s\S]*flex-wrap: nowrap;[\s\S]*justify-content: flex-start;[\s\S]*margin-left: clamp\(1\.25rem, 2vw, 2\.15rem\);/);
  assert.match(css, /\.story-brand\s*\{[\s\S]*font-family: var\(--font-display\);[\s\S]*font-size: clamp\(2rem, 2\.38vw, 3rem\);[\s\S]*white-space: nowrap;/);
  assert.match(css, /\.story-section--hero \.nav-pill\s*\{[\s\S]*border-width: 3px;[\s\S]*font-size: clamp\(0\.72rem, 0\.82vw, 0\.95rem\);[\s\S]*min-height: clamp\(2\.45rem, 2\.8vw, 2\.9rem\);/);
  assert.match(css, /@media \(max-width: 1100px\)[\s\S]*\.story-section--hero \.story-nav__links\s*\{[\s\S]*flex-wrap: wrap;/);
  assert.match(css, /\.hero-poster \.micro-label\s*\{[\s\S]*display: flex;[\s\S]*font-family: var\(--font-mono\);[\s\S]*font-size: clamp\(0\.82rem, 0\.98vw, 1\.18rem\);[\s\S]*letter-spacing: 0\.16em;/);
  assert.match(css, /\.hero-poster \.micro-label strong\s*\{[\s\S]*background: var\(--ink\);[\s\S]*border-radius: 999px;[\s\S]*color: var\(--yellow\);/);
  assert.match(css, /\.hero-poster \.micro-label span\s*\{\s*margin-left: 0;\s*\}/);
  assert.match(css, /\.hero-poster\s*\{[\s\S]*--hero-title-line-height: 0\.88;[\s\S]*--hero-title-size: clamp\(4\.8rem, 13\.6vw, 17\.5rem\);[\s\S]*max-width: none;[\s\S]*width: 100%;/);
  assert.match(css, /\.hero-poster h1\s*\{[\s\S]*font-size: var\(--hero-title-size\);[\s\S]*line-height: var\(--hero-title-line-height\);/);
  assert.match(css, /\.hero-poster h1 span\s*\{\s*transform: translateY\(clamp\(0\.7rem, 0\.72vw, 1rem\)\);\s*\}/);
  assert.match(css, /\.hero-dots\s*\{[\s\S]*height: calc\(var\(--hero-title-size\) \* var\(--hero-title-line-height\) \* 2\);[\s\S]*pointer-events: none;[\s\S]*position: absolute;/);
  assert.match(css, /\.hero-dots i:nth-child\(1\)\s*\{[\s\S]*left: 75%;[\s\S]*top: 32%;/);
  assert.match(css, /\.hero-dots i:nth-child\(2\)\s*\{[\s\S]*left: 85\.5%;[\s\S]*top: 42%;/);
  assert.match(css, /\.hero-dots i:nth-child\(3\)\s*\{[\s\S]*left: 68%;[\s\S]*top: 63%;/);
  assert.match(css, /\.hero-dots i:nth-child\(4\)\s*\{[\s\S]*left: 90\.4%;[\s\S]*top: 52%;/);
  assert.doesNotMatch(css, /\.hero-poster h1::after/);
  assert.match(css, /@media \(max-width: 760px\)[\s\S]*\.hero-poster h1 span\s*\{\s*transform: none;\s*\}/);
  assert.match(css, /\.section-kicker,[\s\S]*\.chart-axis-note\s*\{[\s\S]*font-family: var\(--font-mono\);/);
  assert.match(css, /\.axis-label\s*\{[\s\S]*font-family: var\(--font-chart\);/);
  assert.match(css, /\.report-section-heading h4\s*\{[\s\S]*font-family: var\(--font-airbnb-extra-bold\);/);
  assert.match(css, /\.selected-heading__select/);
  assert.ok(css.indexOf(".selected-heading__select.restaurant-select") > css.indexOf(".restaurant-select {\n  background: var(--paper);"));
  assert.match(css, /\.selected-heading__control::after\s*\{[\s\S]*border-top: clamp\([^;]+ solid var\(--paper\);/);
  assert.match(css, /\.selected-heading__select\.restaurant-select\s*\{[\s\S]*background: var\(--orange\);[\s\S]*color: var\(--paper\);/);
  assert.match(css, /\.selected-heading__select\.restaurant-select\s*\{[\s\S]*appearance: none;/);
  assert.match(css, /\.map-chart--kakao/);
  assert.match(css, /\.kakao-map-canvas/);
  assert.match(css, /\.kakao-map-marker--selected/);
  assert.match(css, /\.kakao-map-popup/);
  assert.doesNotMatch(css, /\.selected-heading > span/);
  assert.match(css, /max-height: var\(--qna-answer-height\)/);
  assert.match(css, /prefers-reduced-motion: reduce/);
  assert.match(css, /max-height 280ms ease/);
  assert.match(css, /a0\.muscache\.com\/airbnb\/static\/airbnb-dls-web\/build\/fonts\/cereal-variable\/AirbnbCerealVF_W_Wght/);
  assert.ok(css.indexOf(".keyword-chip.keyword-chip--active") > css.indexOf(".keyword-chip {\n  background: var(--paper-soft);\n}"));
  assert.match(css, /\.keyword-chip\.keyword-chip--active\s*\{\s*background: var\(--orange\);\s*color: var\(--paper\);/);
  assert.match(layout, /rel="preconnect"/);
  assert.match(layout, /https:\/\/fonts\.googleapis\.com/);
  assert.match(layout, /https:\/\/fonts\.gstatic\.com/);
  assert.match(layout, /family=Bowlby\+One&family=Inter:wght@400;700&family=JetBrains\+Mono:wght@400;700&family=Noto\+Sans\+KR:wght@400;700&family=Sora:wght@400;600;700;800&display=swap/);
  assert.match(layout, /https:\/\/cdn\.jsdelivr\.net/);
  assert.match(layout, /https:\/\/a0\.muscache\.com/);
  assert.doesNotMatch(css, /Georgia|"Courier New"/);
  assert.doesNotMatch(css, /\.qna__answer\s*\{[^}]*display:\s*none/s);
  assert.doesNotMatch(experience, /Loading Hidden Bites data story/);
  assert.doesNotMatch(experience, /seoul-top-restaurants\.png/);
  assert.match(experience, /src="\/figma\/question-preview-collage\.png"/);
  assert.doesNotMatch(`${experience}\n${scorePlot}\n${seoulMap}\n${reportPanel}`, /Alert\.alert|as any/);
});
