import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";

test("client implements the required story surfaces", async () => {
  const page = await readFile("app/page.tsx", "utf8");
  const layout = await readFile("app/layout.tsx", "utf8");
  const experience = await readFile("components/HiddenBitesExperience.tsx", "utf8");
  const scorePlot = await readFile("components/ScorePlot.tsx", "utf8");
  const seoulMap = await readFile("components/SeoulRestaurantMap.tsx", "utf8");
  const reportPanel = await readFile("components/RestaurantReportPanel.tsx", "utf8");
  const css = await readFile("app/globals.css", "utf8");

  assert.match(page, /HiddenBitesExperience/);
  assert.match(experience, /story-section--hero/);
  assert.match(experience, /story-section--question/);
  assert.match(experience, /story-section--qna/);
  assert.match(experience, /story-section--scores/);
  assert.match(experience, /story-section--report/);
  assert.match(experience, /story-section--map/);
  assert.match(experience, /story-section--limitations/);
  assert.match(experience, /QnaAccordion/);
  assert.match(experience, /ScorePlot/);
  assert.match(experience, /SeoulRestaurantMap/);
  assert.match(experience, /RestaurantReportPanel/);
  assert.match(scorePlot, /score-controls/);
  assert.match(scorePlot, /factor-weight-slider/);
  assert.match(scorePlot, /score-mode-toggle/);
  assert.match(scorePlot, /role="button"/);
  assert.match(seoulMap, /data-testid="seoul-map-chart"/);
  assert.match(seoulMap, /Seoul top restaurant dot distribution graph/);
  assert.match(seoulMap, /latitude/);
  assert.match(seoulMap, /longitude/);
  assert.match(reportPanel, /restaurant-select/);
  assert.match(reportPanel, /keyword-chip/);
  assert.match(css, /100svh/);
  assert.match(css, /font-family: "WAGURI"/);
  assert.match(css, /WAGURITTF\.woff2/);
  assert.match(css, /unicode-range:/);
  assert.match(css, /U\+AC00-D7A3/);
  assert.match(css, /--font-primary: "WAGURI", "Airbnb Cereal"/);
  assert.match(css, /a0\.muscache\.com\/airbnb\/static\/airbnb-dls-web\/build\/fonts\/cereal-variable\/AirbnbCerealVF_W_Wght/);
  assert.match(layout, /rel="preconnect"/);
  assert.match(layout, /https:\/\/cdn\.jsdelivr\.net/);
  assert.match(layout, /https:\/\/a0\.muscache\.com/);
  assert.doesNotMatch(css, /Georgia|"Courier New"/);
  assert.doesNotMatch(experience, /Loading Hidden Bites data story/);
  assert.doesNotMatch(experience, /seoul-top-restaurants\.png|<img/);
  assert.doesNotMatch(`${experience}\n${scorePlot}\n${seoulMap}\n${reportPanel}`, /Alert\.alert|as any/);
});
