import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";

test("selected report section follows the Figma interaction and visual contract", async () => {
  const experience = await readFile("components/HiddenBitesExperience.tsx", "utf8");
  const reportPanel = await readFile("components/RestaurantReportPanel.tsx", "utf8");
  const css = await readFile("app/globals.css", "utf8");

  assert.match(experience, /const selectedRestaurantPickerId = "selected-restaurant-picker"/);
  assert.match(experience, /const selectedRestaurantDropdownButtonId = "selected-restaurant-picker-button"/);
  assert.match(experience, /document\.getElementById\(selectedRestaurantPickerId\)\?\.scrollIntoView\(\{ behavior: "smooth", block: "start" \}\)/);
  assert.match(experience, /document\.getElementById\(selectedRestaurantDropdownButtonId\)\?\.focus\(\{ preventScroll: true \}\)/);
  assert.match(experience, /aria-haspopup="listbox"/);
  assert.match(experience, /role="listbox"/);
  assert.match(experience, /className="selected-heading__description"/);
  assert.match(experience, /The report links macro emotional adjective patterns with micro keyword evidence from original reviews\.<\/p>\s*<p>Selecting another dot in HB Scores would refresh this panel\.<\/p>/);
  assert.doesNotMatch(experience, /id="selected-report-restaurant-select"|selected-heading__select restaurant-select/);

  assert.ok(reportPanel.indexOf("<h3>{report.displayPlaceName}</h3>") < reportPanel.indexOf("restaurant-report-meta"));
  assert.match(reportPanel, /<span aria-label=\{`\$\{report\.googlePlaceRating\.toFixed\(1\)\} star rating`\}>★★★★★<\/span>/);
  assert.match(reportPanel, /<strong>\{report\.googlePlaceRating\.toFixed\(1\)\}<\/strong>/);
  assert.match(reportPanel, /Macro analysis: Categories were defined/);
  assert.match(reportPanel, /<strong>by selecting the top 10 most frequent adjective<\/strong>/);
  assert.match(reportPanel, /<span>s for each category\.<\/span>/);
  assert.match(reportPanel, /buildAdjectiveDisplayBuckets\(report\.adjectiveBuckets\)/);
  assert.match(reportPanel, /const \[openEmotionCategoryId, setOpenEmotionCategoryId\] = useState<string \| null>\(null\)/);
  assert.match(reportPanel, /<span>Emotion Category<\/span>/);
  assert.match(reportPanel, /aria-label="Review emotion categories"/);
  assert.match(reportPanel, /aria-expanded=\{isOpen\}/);
  assert.match(reportPanel, /onClick=\{\(\) => setOpenEmotionCategoryId\(isOpen \? null : bucket\.id\)\}/);
  assert.match(reportPanel, /<ChevronDown aria-hidden="true" className=\{isOpen \? "emotion-chip__chevron emotion-chip__chevron--open" : "emotion-chip__chevron"\} size=\{18\} \/>/);
  assert.match(reportPanel, /formatEmotionCategoryWords\(bucket\.adjectives\)/);
  assert.match(reportPanel, /adjectives: bucket\.adjectives/);
  assert.match(reportPanel, /averageSharePercent: bucket\.averageShare \* 100/);
  assert.match(reportPanel, /buildMarkerStyle\(bucket\.sharePercent, bucket\.averageSharePercent, graphMaxPercent\)/);
  assert.match(reportPanel, /relief:\s*\{[\s\S]*label: "Relief"[\s\S]*color: "#4d8ccf"/);
  assert.match(reportPanel, /regret:\s*\{[\s\S]*label: "Regret"[\s\S]*color: "#ff8fb1"/);
  assert.match(reportPanel, /<strong>Click a funny category chip<\/strong>/);
  assert.match(reportPanel, /report\.funnyKeywords\.map\(\(keyword\) =>/);
  assert.match(reportPanel, /buildFunnyKeywordFooter\(snippet, funnyKeywordEvidence\)/);
  assert.match(reportPanel, /return `CATEGORY: \$\{keyword\.label\} · MATCH: \$\{snippet\.matchedTerms\.slice\(0, 5\)\.join\(" · "\)\}`/);
  assert.doesNotMatch(reportPanel, /buildKeywordFooter|keywordEvidence|selectedKeyword|report\.keywords\.map/);
  assert.match(reportPanel, /className="emotion-graph__header"/);
  assert.match(reportPanel, /Emotion Graph/);
  assert.match(reportPanel, /category share \(%\)/);
  assert.match(reportPanel, /vs all-50 average/);
  assert.match(reportPanel, /className="emotion-graph__marker"/);
  assert.match(reportPanel, /className="emotion-graph__bar"/);
  assert.match(reportPanel, /className="emotion-graph__bar-value"/);
  assert.match(reportPanel, /className="restaurant-explorer"/);
  assert.match(reportPanel, /<button type="button" onClick=\{onExploreAnotherRestaurant\}>/);
  assert.doesNotMatch(reportPanel, /<select|ExternalLink|googleMapsUri|restaurant-select/);

  assert.match(css, /\.selected-restaurant-dropdown__menu\s*\{[\s\S]*font-size: 16px;|\.selected-restaurant-dropdown__option strong\s*\{[\s\S]*font-size: 16px;/);
  assert.match(css, /\.selected-heading\s*\{[\s\S]*max-width: min\(100%, 112rem\);/);
  assert.match(css, /\.selected-heading__description\s*\{[\s\S]*display: grid;[\s\S]*max-width: min\(100%, 112rem\);/);
  assert.match(css, /\.selected-heading__description p\s*\{[\s\S]*max-width: none;[\s\S]*white-space: nowrap;/);
  assert.match(css, /@media \(max-width: 1100px\)[\s\S]*\.selected-heading__description p\s*\{[\s\S]*white-space: normal;/);
  assert.match(css, /\.restaurant-report-meta\s*\{[\s\S]*font-family: var\(--font-mono\);[\s\S]*white-space: nowrap;/);
  assert.match(css, /\.restaurant-rating span\s*\{[\s\S]*font-family: var\(--font-body\);[\s\S]*font-size: 22px;[\s\S]*letter-spacing: 1px;/);
  assert.match(css, /\.restaurant-rating strong\s*\{[\s\S]*font-family: var\(--font-display\);[\s\S]*font-size: 44px;[\s\S]*line-height: 44px;/);
  assert.match(css, /\.report-section-heading p strong\s*\{[\s\S]*font-weight: 800;[\s\S]*text-decoration: underline;/);
  assert.match(css, /\.funny-keyword-summary\s*\{[\s\S]*font-family: var\(--font-mono\);/);
  assert.match(css, /\.emotion-category > span\s*\{[\s\S]*font-family: var\(--font-mono\);[\s\S]*font-size: 12px;/);
  assert.match(css, /\.emotion-chip-row\s*\{[\s\S]*align-items: start;[\s\S]*grid-template-columns: repeat\(7, minmax\(128px, 1fr\)\);[\s\S]*overflow-x: auto;/);
  assert.match(css, /\.emotion-chip\s*\{[\s\S]*border: 0;[\s\S]*display: grid;[\s\S]*text-align: left;/);
  assert.match(css, /\.emotion-chip--open\s*\{[\s\S]*min-height: 174px;/);
  assert.match(css, /\.emotion-chip__words\s*\{[\s\S]*font-family: var\(--font-korean\);[\s\S]*font-size: 11px;[\s\S]*max-height: 0;/);
  assert.match(css, /\.emotion-chip--open \.emotion-chip__words\s*\{[\s\S]*max-height: 96px;[\s\S]*opacity: 1;/);
  assert.match(css, /\.emotion-graph__plot\s*\{[\s\S]*height: 480px;[\s\S]*overflow-x: auto;[\s\S]*overflow-y: hidden;/);
  assert.match(css, /\.emotion-graph__bars\s*\{[\s\S]*grid-template-columns: repeat\(7, 1fr\);[\s\S]*min-width: 980px;/);
  assert.match(css, /\.emotion-graph__grid span\s*\{[\s\S]*border-top: 2px solid rgba\(26, 19, 16, 0\.12\);/);
  assert.match(css, /\.emotion-graph__marker\s*\{[\s\S]*transform: rotate\(45deg\);/);
  assert.match(css, /\.emotion-graph__bar\s*\{[\s\S]*border-radius: 999px 999px 0 0;[\s\S]*width: 76px;/);
  assert.match(css, /\.emotion-graph__bar-value\s*\{[\s\S]*font-family: var\(--font-chart\);/);
  assert.match(css, /\.emotion-graph__column small\s*\{[\s\S]*font-family: var\(--font-korean\);/);
  assert.match(css, /\.snippet\s*\{[\s\S]*border-radius: 22px;[\s\S]*padding: 22px 24px;/);
  assert.match(css, /\.snippet--funny\s*\{[\s\S]*border: 2px solid rgba\(26, 19, 16, 0\.18\);/);
  assert.match(css, /\.snippet footer\s*\{[\s\S]*font-family: var\(--font-mono\);[\s\S]*font-size: 12px;/);
  assert.match(css, /\.funny-keyword-empty\s*\{[\s\S]*border: 2px dashed rgba\(26, 19, 16, 0\.22\);/);
  assert.match(css, /\.restaurant-explorer button\s*\{[\s\S]*border-radius: 20px;[\s\S]*font-family: var\(--font-airbnb-bold\);/);
});
